---
title: "Mode Share"
date: today
---

In [1]:
import pandas as pd
import numpy as np
import toml
from pathlib import Path
from sqlalchemy import create_engine

config = toml.load(Path.cwd() / '../../../../configuration/input_configuration.toml')
summary_config = toml.load(Path.cwd() / '../../../../configuration/summary_configuration.toml')

pd.set_option('display.float_format', '{:,.1%}'.format)

In [2]:
# Relative path between notebooks and goruped output directories
output_path = Path(summary_config['sc_run_path']) / summary_config["output_folder"]
survey_path = Path(summary_config['sc_run_path']) / summary_config["survey_folder"]

In [3]:
# add trip type to trip tables
def prep_trip_df(trip):
    df_trip = trip.copy()
    df_trip.rename(columns={'mode':'Mode'}, inplace=True)
    df_trip['Trip Type'] = 'Non-Work'
    df_trip.loc[df_trip['dpurp'] == 'Work', 'Trip Type'] = 'Work'

    # add all tripa
    df = df_trip.copy()
    df['Trip Type'] = 'All Trips'
    df_trip = pd.concat([df_trip.sort_values('Trip Type'), df], ignore_index=True)

    return df_trip

In [4]:
person = pd.read_csv(output_path / 'agg/dash/person_geog.csv')

# counties
trip_county = prep_trip_df(pd.read_csv(output_path / 'agg/dash/mode_share_county.csv'))
# remove "Outside Region"
trip_county = trip_county[trip_county['hh_county'] != 'Outside Region']
# regional geographies
trip_rg = prep_trip_df(pd.read_csv(output_path / 'agg/dash/mode_share_rg.csv'))
# centers
trip_rgc = pd.read_csv(output_path / 'agg/dash/mode_share_rgc.csv')
# add all RGCs
df = trip_rgc[trip_rgc['hh_rgc'] != 'Not in RGC'].groupby(['dpurp','mode']).sum()[['trexpfac']].reset_index()
df['hh_rgc'] = 'All RGCs'
trip_rgc = pd.concat([df, trip_rgc])
trip_rgc = prep_trip_df(trip_rgc)

In [5]:
# equity geographies
equity_geogs = summary_config['hh_equity_geogs']
trip_equity_geog = pd.DataFrame()
for geog in equity_geogs:
    df = prep_trip_df(pd.read_csv(output_path/ ('agg/dash/mode_share_'+geog+'.csv')))
    df['equity_geog'] = df[geog].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'})
    
    trip_equity_geog = pd.concat([trip_equity_geog, df[['dpurp', 'Mode', 'equity_geog', 'trexpfac', 'Trip Type']]])

## regional mode share

In [6]:
df1 = trip_county.groupby(['Trip Type','Mode'],as_index=False)['trexpfac'].sum()
df2 = trip_county.groupby(['Trip Type'],as_index=False)['trexpfac'].sum()
df2.rename(columns={'trexpfac':'total_trips'}, inplace=True)

df = df1.merge(df2, on='Trip Type')
df['mode_share'] = df['trexpfac'] / df['total_trips']

df.pivot_table(columns='Mode', index='Trip Type', values='mode_share')

Mode       Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
Trip Type
All Trips  1.5% 21.3%  14.1% 44.5%        1.6% 0.3%     2.2% 14.4%
Non-Work   1.5% 23.2%  15.4% 40.4%        1.8% 0.3%     2.2% 15.3%
Work       1.4%  9.4%   5.8% 71.6%        0.0% 0.6%     2.3%  8.9%

## trip mode share by home location

:::{.panel-tabset}

### County

In [7]:
def calc_mode_share(df_trip, geog):
    
    # num trips by mode
    df1 = df_trip.groupby([geog, 'Trip Type', 'Mode'],as_index=False)['trexpfac'].sum()
    # num trips
    df2 = df_trip.groupby([geog, 'Trip Type'],as_index=False)['trexpfac'].sum()
    df2.rename(columns={'trexpfac':'total_trips'}, inplace=True)

    df = df1.merge(df2, on=[geog, 'Trip Type'])
    # mode share
    df['mode_share'] = df['trexpfac'] / df['total_trips']

    # mode share by trip type
    df_all = df.loc[df['Trip Type']=="All Trips"].pivot_table(columns='Mode', index=geog, values='mode_share')
    df_work = df.loc[df['Trip Type']=="Work"].pivot_table(columns='Mode', index=geog, values='mode_share')
    df_non_work = df.loc[df['Trip Type']=="Non-Work"].pivot_table(columns='Mode', index=geog, values='mode_share')
    # num trips by trip type
    trip_all = df.loc[df['Trip Type']=="All Trips"].pivot_table(columns='Mode', index=geog, values='trexpfac')
    trip_work = df.loc[df['Trip Type']=="Work"].pivot_table(columns='Mode', index=geog, values='trexpfac')
    trip_non_work = df.loc[df['Trip Type']=="Non-Work"].pivot_table(columns='Mode', index=geog, values='trexpfac')

    return df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work


df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work = calc_mode_share(trip_county,'hh_county')

:::{.panel-tabset}

#### All Purposes

In [8]:
df_all

Mode       Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
hh_county
King       1.7% 20.2%  13.2% 43.4%        1.5% 0.4%     3.3% 16.4%
Kitsap     1.2% 22.2%  14.3% 45.2%        1.5% 0.2%     1.3% 14.2%
Pierce     1.4% 23.1%  15.5% 45.0%        1.9% 0.2%     0.8% 12.1%
Snohomish  1.3% 22.5%  15.2% 46.9%        1.7% 0.2%     0.8% 11.4%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [9]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [10]:
df_non_work

Mode       Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
hh_county
King       1.7% 22.0%  14.4% 39.2%        1.7% 0.3%     3.3% 17.3%
Kitsap     1.3% 23.8%  15.3% 41.7%        1.6% 0.2%     0.9% 15.1%
Pierce     1.4% 24.8%  16.8% 40.9%        2.1% 0.2%     0.7% 13.0%
Snohomish  1.3% 24.3%  16.6% 42.5%        1.9% 0.2%     0.9% 12.4%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [11]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [12]:
df_work

Mode       Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
hh_county
King       1.7%  9.0%   5.6% 68.5%        0.0% 0.8%     2.9% 11.5%
Kitsap     0.9%  9.4%   5.8% 72.6%        0.0% 0.2%     4.0%  7.1%
Pierce     1.0%  9.9%   6.2% 76.0%        0.0% 0.3%     1.2%  5.3%
Snohomish  1.0% 10.0%   6.3% 76.9%        0.0% 0.2%     0.7%  4.9%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [13]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Regional Growth Center

:::{.panel-tabset}

#### All Purposes

In [14]:
df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_rgc, 'hh_rgc')

df_all

Mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
hh_rgc,,,,,,,,
All RGCs,3.0%,10.7%,5.2%,29.1%,0.5%,1.5%,6.5%,43.4%
Auburn,2.6%,18.6%,10.2%,38.9%,1.1%,0.5%,3.4%,24.7%
Bellevue,2.6%,11.2%,5.1%,31.6%,0.4%,0.9%,3.5%,44.7%
Bothell Canyon Park,1.4%,20.8%,11.4%,51.1%,1.6%,0.4%,0.6%,12.8%
Bremerton,2.5%,14.8%,7.3%,35.7%,0.4%,0.5%,2.2%,36.6%
Burien,2.0%,17.2%,9.5%,44.4%,0.8%,0.4%,3.0%,22.8%
Everett,2.0%,13.4%,6.8%,38.5%,0.7%,0.4%,2.1%,36.1%
Federal Way,1.9%,21.2%,14.9%,35.8%,1.9%,NaN,1.9%,22.4%
Greater Downtown Kirkland,1.9%,17.4%,8.3%,47.3%,0.7%,0.4%,3.8%,20.1%
Kent,1.9%,18.1%,11.9%,36.6%,1.5%,0.6%,4.2%,25.2%
Kirkland Totem Lake,1.9%,19.2%,10.2%,49.4%,1.0%,0.3%,1.6%,16.3%
Lakewood,2.1%,22.0%,9.4%,38.4%,1.7%,0.6%,1.1%,24.7%
Lynnwood,1.7%,19.0%,11.5%,43.5%,1.4%,0.5%,2.3%,20.1%
Not in RGC,1.4%,22.1%,14.8%,45.6%,1.7%,0.2%,1.9%,12.3%
Puyallup Downtown,1.3%,18.7%,10.1%,40.5%,0.9%,0.5%,2.0%,26.0%
Puyallup South Hill,1.4%,19.1%,10.3%,44.6%,1.6%,0.5%,1.3%,21.3%
Redmond Downtown,2.5%,15.1%,8.1%,44.1%,0.8%,0.4%,1.8%,27.2%
Redmond-Overlake,2.5%,15.8%,8.9%,40.9%,1.0%,0.4%,2.3%,28.2%
Renton,2.3%,17.1%,8.0%,45.9%,0.8%,0.4%,3.1%,22.4%
SeaTac,1.9%,20.0%,13.2%,39.6%,1.8%,0.2%,6.4%,16.9%
Seattle Downtown,3.2%,4.9%,1.7%,12.5%,0.1%,3.0%,7.1%,67.5%
Seattle First Hill/Capitol Hill,3.6%,6.1%,2.3%,18.7%,0.2%,2.6%,9.5%,57.0%
Seattle Northgate,2.2%,15.3%,7.1%,40.7%,0.6%,0.6%,10.7%,22.8%
Seattle South Lake Union,3.6%,6.4%,2.1%,21.1%,0.1%,2.2%,6.8%,57.7%
Seattle University Community,5.0%,8.0%,4.0%,30.1%,0.2%,0.8%,16.7%,35.2%
Seattle Uptown,4.0%,9.0%,3.1%,29.2%,0.2%,1.3%,6.6%,46.6%
Silverdale,1.8%,14.6%,7.6%,44.0%,1.4%,0.4%,0.7%,29.4%
Tacoma Downtown,2.6%,12.7%,5.9%,35.8%,0.5%,0.7%,3.1%,38.8%
Tacoma Mall,2.7%,17.9%,10.1%,37.9%,1.7%,0.9%,2.3%,26.4%
Tukwila,1.9%,14.4%,5.2%,52.4%,NaN,0.4%,3.1%,22.7%
University Place,2.0%,19.5%,10.7%,46.0%,1.7%,0.4%,1.2%,18.6%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [15]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [16]:
df_non_work

Mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
hh_rgc,,,,,,,,
All RGCs,3.0%,11.9%,5.7%,26.2%,0.6%,1.3%,7.0%,44.4%
Auburn,2.5%,19.9%,10.8%,35.8%,1.2%,0.4%,3.1%,26.3%
Bellevue,2.6%,12.3%,5.5%,28.1%,0.5%,0.7%,3.8%,46.4%
Bothell Canyon Park,1.3%,22.5%,12.5%,46.8%,1.9%,0.4%,0.4%,14.2%
Bremerton,2.5%,15.9%,7.7%,32.2%,0.4%,0.5%,1.5%,39.3%
Burien,1.9%,18.6%,10.1%,39.7%,0.9%,0.4%,3.2%,25.3%
Everett,1.9%,14.4%,7.4%,34.1%,0.8%,0.4%,2.2%,38.7%
Federal Way,1.9%,22.2%,16.0%,32.2%,2.1%,NaN,2.0%,23.7%
Greater Downtown Kirkland,1.9%,18.9%,9.1%,43.1%,0.9%,0.4%,3.8%,22.0%
Kent,1.7%,19.3%,12.8%,32.8%,1.8%,0.7%,4.1%,26.9%
Kirkland Totem Lake,1.9%,20.9%,11.2%,44.8%,1.2%,0.3%,1.7%,17.9%
Lakewood,1.9%,23.6%,10.3%,33.8%,1.9%,0.6%,1.1%,26.7%
Lynnwood,1.7%,20.5%,12.3%,39.2%,1.7%,0.6%,2.5%,21.7%
Not in RGC,1.4%,24.0%,16.0%,41.4%,1.9%,0.2%,1.8%,13.3%
Puyallup Downtown,1.4%,19.7%,10.6%,36.9%,1.0%,0.5%,1.9%,28.0%
Puyallup South Hill,1.5%,20.5%,11.2%,39.9%,1.8%,0.5%,1.2%,23.4%
Redmond Downtown,2.4%,16.7%,8.9%,38.8%,0.9%,0.4%,1.9%,29.8%
Redmond-Overlake,2.3%,17.3%,9.7%,36.0%,1.2%,0.4%,2.4%,30.6%
Renton,2.3%,18.9%,8.6%,41.4%,0.9%,0.4%,3.5%,24.0%
SeaTac,1.9%,21.5%,14.3%,36.0%,2.0%,0.2%,6.4%,17.7%
Seattle Downtown,3.2%,5.4%,1.9%,11.0%,0.1%,2.5%,8.1%,67.8%
Seattle First Hill/Capitol Hill,3.6%,6.7%,2.5%,16.3%,0.3%,2.1%,10.3%,58.1%
Seattle Northgate,2.1%,16.8%,7.7%,36.8%,0.7%,0.6%,10.5%,24.8%
Seattle South Lake Union,3.5%,7.2%,2.3%,18.6%,0.1%,1.8%,7.7%,58.7%
Seattle University Community,5.1%,8.5%,4.1%,25.5%,0.3%,0.7%,17.3%,38.6%
Seattle Uptown,3.9%,10.0%,3.4%,25.9%,0.2%,1.0%,7.3%,48.3%
Silverdale,1.7%,15.7%,8.4%,40.1%,1.6%,0.4%,0.5%,31.5%
Tacoma Downtown,2.5%,13.7%,6.3%,32.1%,0.6%,0.7%,3.2%,40.9%
Tacoma Mall,2.6%,19.0%,10.8%,34.0%,1.9%,1.0%,2.2%,28.4%
Tukwila,1.7%,16.3%,5.4%,47.3%,NaN,0.4%,3.1%,25.8%
University Place,2.0%,21.1%,11.5%,41.7%,1.9%,0.3%,1.2%,20.2%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [17]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [18]:
df_work

Mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
hh_rgc,,,,,,,,
All RGCs,3.2%,5.3%,2.5%,43.4%,0.0%,2.7%,4.5%,38.4%
Auburn,3.5%,7.9%,5.2%,64.2%,NaN,0.9%,6.5%,11.7%
Bellevue,2.9%,5.6%,2.7%,49.3%,NaN,1.6%,1.9%,35.9%
Bothell Canyon Park,1.8%,11.2%,5.1%,75.6%,NaN,0.3%,1.3%,4.8%
Bremerton,2.9%,7.4%,4.1%,59.4%,NaN,0.4%,6.7%,19.2%
Burien,2.6%,9.2%,6.2%,72.1%,NaN,0.5%,1.9%,7.5%
Everett,2.2%,7.2%,2.9%,67.1%,NaN,0.4%,1.0%,19.2%
Federal Way,1.5%,13.4%,6.5%,64.9%,NaN,NaN,1.1%,12.6%
Greater Downtown Kirkland,2.1%,8.6%,3.9%,72.3%,NaN,0.5%,3.6%,9.1%
Kent,3.2%,9.5%,5.7%,63.9%,NaN,0.1%,4.5%,13.1%
Kirkland Totem Lake,1.9%,8.9%,4.3%,76.3%,NaN,0.3%,0.9%,7.4%
Lakewood,3.1%,9.8%,2.7%,73.0%,NaN,0.4%,0.8%,10.2%
Lynnwood,1.8%,9.8%,6.0%,70.2%,NaN,0.3%,1.3%,10.5%
Not in RGC,1.2%,9.8%,6.2%,74.4%,0.0%,0.3%,2.0%,6.1%
Puyallup Downtown,0.5%,10.7%,5.6%,70.2%,NaN,0.5%,2.8%,9.8%
Puyallup South Hill,0.9%,10.2%,4.9%,73.3%,NaN,0.2%,2.3%,8.1%
Redmond Downtown,3.0%,6.8%,3.8%,70.4%,NaN,0.6%,1.1%,14.2%
Redmond-Overlake,3.1%,8.1%,4.7%,65.7%,NaN,0.6%,1.6%,16.2%
Renton,2.4%,6.4%,4.2%,72.8%,NaN,0.6%,0.8%,12.7%
SeaTac,2.2%,9.7%,6.1%,64.1%,NaN,0.3%,6.1%,11.6%
Seattle Downtown,3.0%,2.9%,1.1%,18.6%,NaN,5.0%,3.0%,66.5%
Seattle First Hill/Capitol Hill,3.8%,3.7%,1.4%,28.6%,NaN,4.5%,6.1%,52.0%
Seattle Northgate,2.3%,7.6%,3.7%,62.0%,NaN,0.8%,12.0%,11.7%
Seattle South Lake Union,3.8%,3.4%,1.4%,30.4%,NaN,3.7%,3.3%,54.0%
Seattle University Community,4.8%,5.2%,3.2%,54.6%,0.0%,1.5%,13.5%,17.3%
Seattle Uptown,4.7%,5.2%,1.5%,43.0%,NaN,2.2%,3.9%,39.4%
Silverdale,2.5%,7.8%,3.0%,68.1%,NaN,0.3%,1.5%,16.8%
Tacoma Downtown,2.8%,6.4%,3.1%,59.5%,NaN,0.7%,2.4%,25.2%
Tacoma Mall,3.7%,9.7%,4.5%,67.0%,NaN,0.5%,3.4%,11.2%
Tukwila,2.8%,5.9%,4.4%,74.2%,NaN,0.4%,3.3%,9.0%
University Place,2.0%,8.4%,5.0%,74.8%,NaN,0.5%,1.2%,8.2%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [19]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Regional Geography

:::{.panel-tabset}

#### All Purposes

In [20]:
df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_rg, 'hh_rg_proposed')

df_all

Mode            Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
hh_rg_proposed
CitiesTowns     1.2% 22.7%  16.5% 45.0%        2.1% 0.2%     0.6% 11.7%
Core            1.4% 22.2%  14.8% 45.7%        1.7% 0.2%     1.8% 12.1%
HCT             1.3% 22.6%  15.3% 46.2%        1.8% 0.2%     1.4% 11.3%
Metro           2.1% 17.8%  10.7% 40.1%        1.2% 0.6%     4.4% 23.2%
UU              1.2% 24.2%  17.7% 44.9%        2.1% 0.2%     0.5%  9.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [21]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [22]:
df_non_work

Mode            Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
hh_rg_proposed
CitiesTowns     1.2% 24.5%  17.9% 40.6%        2.4% 0.2%     0.5% 12.7%
Core            1.4% 24.1%  16.1% 41.3%        2.0% 0.2%     1.8% 13.1%
HCT             1.4% 24.4%  16.6% 41.8%        2.1% 0.2%     1.3% 12.2%
Metro           2.0% 19.4%  11.7% 36.1%        1.4% 0.5%     4.5% 24.4%
UU              1.3% 26.0%  19.2% 40.6%        2.4% 0.1%     0.4% 10.0%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [23]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [24]:
df_work

Mode            Bike  HOV2  HOV3+   SOV  School Bus  TNC  Transit  Walk
hh_rg_proposed
CitiesTowns     0.6% 10.3%   6.9% 76.1%        0.0% 0.2%     0.9%  4.9%
Core            1.2%  9.9%   6.4% 74.4%        0.0% 0.3%     2.0%  5.8%
HCT             1.0% 10.0%   6.4% 75.8%        0.0% 0.3%     1.6%  4.9%
Metro           2.3%  8.2%   4.7% 63.4%        0.0% 1.1%     3.7% 16.6%
UU              0.7% 10.2%   6.7% 77.5%         NaN 0.2%     0.9%  3.8%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [25]:
trip_work.style.format("{:0,.0f}")

:::

:::

### Equity Focus Area

In [26]:
equity_geogs = summary_config['hh_equity_geogs']

trip_equity_geog = pd.DataFrame()

for geog in equity_geogs:
    df = prep_trip_df(pd.read_csv(output_path/ ('agg/dash/mode_share_'+geog+'.csv')))
    df['equity_geog'] = df[geog].map({
                                0: 'Below Regional Average', 
                                1: 'Above Regional Average', 
                                2: 'Higher Share of Equity Population'})
    
    trip_equity_geog = pd.concat([trip_equity_geog, df[['dpurp', 'Mode', 'equity_geog', 'trexpfac', 'Trip Type']]])

df_all, df_work, df_non_work, trip_all, trip_work, trip_non_work  = calc_mode_share(trip_equity_geog, 'equity_geog')

:::{.panel-tabset}

#### All Purposes

In [27]:
df_all

Mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
equity_geog,,,,,,,,
Above Regional Average,1.4%,21.7%,14.4%,44.7%,1.6%,0.3%,2.0%,13.8%
Below Regional Average,1.5%,21.0%,13.8%,44.7%,1.6%,0.3%,2.2%,14.8%
Higher Share of Equity Population,1.5%,21.8%,14.6%,43.2%,1.7%,0.3%,2.3%,14.5%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [28]:
trip_all.style.format("{:0,.0f}")

:::

#### Non-Work Purposes

In [29]:
df_non_work

Mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
equity_geog,,,,,,,,
Above Regional Average,1.5%,23.5%,15.6%,40.6%,1.9%,0.3%,2.0%,14.6%
Below Regional Average,1.5%,22.9%,15.1%,40.6%,1.8%,0.3%,2.2%,15.6%
Higher Share of Equity Population,1.6%,23.5%,15.8%,39.2%,2.0%,0.3%,2.4%,15.3%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [30]:
trip_non_work.style.format("{:0,.0f}")

:::

#### Work

In [31]:
df_work

Mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
equity_geog,,,,,,,,
Above Regional Average,1.3%,9.5%,6.0%,72.2%,0.0%,0.5%,2.0%,8.5%
Below Regional Average,1.5%,9.2%,5.7%,71.4%,0.0%,0.6%,2.4%,9.3%
Higher Share of Equity Population,1.4%,9.7%,6.2%,71.6%,0.0%,0.5%,2.2%,8.4%

::: {.callout-note icon=false collapse=true}

## number of trips by mode

In [32]:
trip_work.style.format("{:0,.0f}")

:::

:::

:::

## mode share by trip destination

::: {.callout-note}

### TODO: add other geographies

- create output for mode share by trip/tour destination geographies and purpose in agg.py

:::

In [33]:
tour_rgc_dest = pd.read_csv(output_path / 'agg/dash/tour_rgc_dest.csv')
trip_rgc_dest = pd.read_csv(output_path / 'agg/dash/trip_rgc_dest.csv')

# order RGCs

# all individual centers
l = tour_rgc_dest['tour_d_rgc'].sort_values().unique().tolist()
l.remove('Not in RGC')
l.remove(np.nan)

# aggregated centers
geog_order = ["Region","In RGC","Not in RGC"]

# combine
geog_order.extend(l)

In [34]:
def get_rgc_location(df, dest_col):
    # regional data
    df_region = df.copy()
    df_region[dest_col] = "Region"

    # aggregated centers
    df_isrgc = df.copy()
    df_isrgc.loc[df_isrgc[dest_col]!="Not in RGC", dest_col] = "In RGC"


    df_rgc = pd.concat([
        df_region,
        df_isrgc,
    # 2025 notes:
    # 7 records in the data are missing both mode and and RGC values
    # remove these records
        df.loc[~df[dest_col].isna()]
        ])

    df_rgc[dest_col] = pd.Categorical(df_rgc[dest_col], ordered=True,
                    categories=geog_order)
    
    return df_rgc

df_tour = get_rgc_location(tour_rgc_dest, 'tour_d_rgc')
df_trip = get_rgc_location(trip_rgc_dest, 'trip_d_rgc')

:::{.panel-tabset}

### RGC

In [35]:
def calc_mode_share_by_rgc(df_trip_geog, geog_col, mode_col, n_trip_col):

    df = df_trip_geog.pivot_table(columns=mode_col, index=geog_col, values=n_trip_col, aggfunc='sum', observed=True)

    df = df.apply(lambda x: x/ df_trip_geog.groupby(geog_col, observed=True)[n_trip_col].sum())

    return df

\[TRIP\] Mode Share for All Purposes by Regional Center (Destination Location)

In [36]:
calc_mode_share_by_rgc(df_trip, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.5%,21.3%,14.1%,44.5%,1.6%,0.3%,2.2%,14.4%
In RGC,1.9%,15.9%,8.9%,41.9%,0.5%,0.8%,5.6%,24.5%
Not in RGC,1.4%,22.4%,15.1%,45.0%,1.8%,0.2%,1.5%,12.5%
Auburn,1.2%,22.0%,12.4%,48.5%,0.5%,0.2%,3.2%,12.0%
Bellevue,1.7%,15.1%,8.8%,42.8%,0.4%,0.5%,2.6%,28.2%
Bothell Canyon Park,1.0%,22.3%,14.4%,54.0%,1.1%,0.2%,0.4%,6.7%
Bremerton,1.5%,15.8%,9.0%,54.2%,0.1%,0.3%,1.7%,17.3%
Burien,1.1%,22.7%,12.4%,46.6%,0.8%,0.2%,2.2%,13.9%
Everett,1.3%,19.2%,11.1%,47.2%,0.6%,0.3%,1.6%,18.8%
Federal Way,0.9%,24.4%,13.2%,48.7%,0.5%,0.1%,2.2%,10.0%
Greater Downtown Kirkland,1.4%,19.8%,11.1%,50.0%,0.7%,0.3%,2.2%,14.6%
Issaquah,0.8%,21.7%,12.4%,56.9%,0.5%,0.2%,0.5%,7.0%
Kent,0.9%,22.6%,13.6%,47.7%,0.9%,0.2%,2.9%,11.1%
Kirkland Totem Lake,1.2%,20.7%,11.6%,54.3%,0.7%,0.2%,1.2%,10.1%
Lakewood,1.0%,25.5%,13.3%,48.1%,0.3%,0.4%,0.7%,10.7%
Lynnwood,1.1%,22.4%,12.4%,52.3%,0.6%,0.3%,1.0%,10.0%
Puyallup Downtown,1.0%,23.8%,14.3%,47.1%,1.2%,0.3%,1.1%,11.3%
Puyallup South Hill,0.9%,23.2%,12.8%,52.2%,0.5%,0.2%,0.3%,9.9%
Redmond Downtown,1.5%,20.6%,12.8%,45.0%,1.2%,0.2%,1.3%,17.4%
Redmond-Overlake,1.4%,16.8%,9.9%,55.9%,0.4%,0.3%,1.5%,13.9%
Renton,1.2%,20.4%,11.7%,52.6%,0.7%,0.3%,1.7%,11.4%
SeaTac,1.4%,18.5%,11.7%,50.5%,0.8%,0.2%,4.1%,12.7%
Seattle Downtown,2.3%,9.4%,5.1%,28.6%,0.2%,1.7%,12.2%,40.4%
Seattle First Hill/Capitol Hill,3.0%,10.1%,5.3%,27.9%,0.3%,1.7%,8.7%,43.0%
Seattle Northgate,1.5%,17.8%,8.1%,45.9%,0.5%,0.4%,10.4%,15.3%
Seattle South Lake Union,2.6%,10.6%,5.2%,36.4%,0.1%,1.2%,7.4%,36.5%
Seattle University Community,3.4%,12.4%,6.8%,39.2%,0.4%,0.5%,12.6%,24.7%
Seattle Uptown,3.2%,12.0%,5.8%,35.1%,0.2%,0.9%,5.2%,37.6%
Silverdale,0.9%,23.9%,13.4%,50.4%,0.9%,0.2%,0.2%,10.0%
Tacoma Downtown,1.7%,15.9%,9.1%,47.8%,0.5%,0.4%,2.6%,22.0%
Tacoma Mall,1.6%,21.9%,11.5%,47.9%,0.7%,0.5%,1.3%,14.6%
Tukwila,0.9%,22.7%,12.4%,55.2%,0.1%,0.2%,2.4%,6.0%
University Place,1.5%,22.2%,12.0%,47.0%,1.1%,0.3%,0.8%,15.0%

\[TRIP\] Mode Share to Work by Regional Center (Destination Location)

In [37]:
df_trip_work = df_trip[df_trip['dpurp'] == 'Work'].copy()
calc_mode_share_by_rgc(df_trip_work, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.4%,9.4%,5.8%,71.6%,0.0%,0.6%,2.3%,8.9%
In RGC,1.8%,8.5%,5.4%,61.9%,0.0%,1.0%,4.9%,16.5%
Not in RGC,1.2%,9.8%,6.1%,76.6%,0.0%,0.3%,0.9%,5.0%
Auburn,1.0%,9.9%,6.7%,74.0%,NaN,0.2%,1.2%,7.1%
Bellevue,1.4%,9.2%,6.0%,65.0%,NaN,0.6%,1.7%,16.0%
Bothell Canyon Park,1.0%,9.5%,5.7%,80.0%,NaN,0.2%,0.2%,3.5%
Bremerton,1.1%,9.9%,6.5%,74.5%,NaN,0.3%,1.6%,6.2%
Burien,1.5%,10.9%,6.0%,73.2%,NaN,0.4%,1.1%,6.9%
Everett,1.2%,9.3%,5.6%,72.4%,NaN,0.3%,0.5%,10.7%
Federal Way,1.0%,9.5%,5.3%,77.0%,NaN,0.1%,0.7%,6.3%
Greater Downtown Kirkland,1.2%,9.8%,6.4%,75.9%,0.0%,0.3%,0.9%,5.6%
Issaquah,0.7%,9.7%,6.5%,77.5%,NaN,0.3%,0.4%,5.0%
Kent,1.0%,10.5%,6.5%,73.2%,0.0%,0.4%,1.4%,7.0%
Kirkland Totem Lake,1.1%,9.3%,6.0%,77.2%,0.0%,0.3%,0.6%,5.5%
Lakewood,1.5%,8.1%,5.8%,76.0%,NaN,0.3%,0.6%,7.7%
Lynnwood,1.3%,9.1%,5.7%,77.0%,NaN,0.3%,0.4%,6.2%
Puyallup Downtown,0.7%,9.3%,6.3%,75.4%,NaN,0.4%,1.2%,6.7%
Puyallup South Hill,0.6%,9.6%,5.9%,77.3%,0.0%,0.1%,0.3%,6.1%
Redmond Downtown,1.5%,8.9%,5.6%,72.4%,NaN,0.3%,0.6%,10.7%
Redmond-Overlake,1.2%,9.3%,6.0%,75.6%,0.0%,0.4%,0.9%,6.5%
Renton,1.1%,9.9%,6.4%,75.1%,0.0%,0.3%,0.9%,6.3%
SeaTac,1.1%,9.9%,6.6%,73.4%,NaN,0.3%,2.3%,6.3%
Seattle Downtown,2.3%,7.1%,4.4%,45.0%,NaN,1.9%,11.6%,27.8%
Seattle First Hill/Capitol Hill,2.2%,8.1%,4.8%,51.3%,NaN,1.5%,5.6%,26.4%
Seattle Northgate,1.8%,9.3%,5.5%,72.6%,NaN,0.5%,2.4%,8.0%
Seattle South Lake Union,2.5%,7.8%,4.8%,56.5%,NaN,1.3%,4.4%,22.7%
Seattle University Community,2.2%,9.4%,5.9%,68.0%,0.0%,0.7%,5.2%,8.6%
Seattle Uptown,2.6%,8.4%,4.8%,57.4%,NaN,1.0%,2.8%,23.1%
Silverdale,1.0%,8.6%,5.4%,75.8%,NaN,0.2%,0.3%,8.7%
Tacoma Downtown,1.6%,9.3%,5.8%,70.1%,NaN,0.3%,1.4%,11.4%
Tacoma Mall,1.7%,9.5%,6.0%,75.1%,NaN,0.4%,0.8%,6.5%
Tukwila,0.9%,10.2%,6.5%,76.4%,NaN,0.4%,1.2%,4.4%
University Place,1.6%,9.1%,6.2%,74.8%,NaN,0.3%,0.7%,7.4%

\[TRIP\] Mode Share for Non-work Purposes by Regional Center (Destination Location)

In [38]:
df_trip_non_work = df_trip[df_trip['dpurp'] != 'Work'].copy()
calc_mode_share_by_rgc(df_trip_non_work, 'trip_d_rgc', 'mode', 'trexpfac')

mode,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
trip_d_rgc,,,,,,,,
Region,1.5%,23.2%,15.4%,40.4%,1.8%,0.3%,2.2%,15.3%
In RGC,1.9%,18.8%,10.3%,34.3%,0.6%,0.7%,5.8%,27.6%
Not in RGC,1.5%,23.9%,16.2%,41.3%,2.0%,0.2%,1.6%,13.4%
Auburn,1.2%,24.2%,13.5%,43.8%,0.6%,0.2%,3.6%,12.9%
Bellevue,1.8%,17.9%,10.2%,32.0%,0.6%,0.4%,3.0%,34.1%
Bothell Canyon Park,1.0%,27.4%,17.9%,43.6%,1.5%,0.2%,0.5%,8.0%
Bremerton,2.0%,21.2%,11.3%,35.5%,0.2%,0.3%,1.9%,27.6%
Burien,1.1%,24.0%,13.1%,43.7%,0.9%,0.2%,2.4%,14.6%
Everett,1.3%,21.9%,12.7%,40.3%,0.8%,0.3%,1.9%,21.0%
Federal Way,0.9%,26.7%,14.5%,44.2%,0.5%,0.1%,2.4%,10.6%
Greater Downtown Kirkland,1.4%,22.1%,12.2%,43.9%,0.9%,0.2%,2.5%,16.7%
Issaquah,0.9%,25.8%,14.3%,50.0%,0.7%,0.2%,0.6%,7.6%
Kent,0.9%,25.0%,15.0%,42.5%,1.0%,0.2%,3.2%,12.0%
Kirkland Totem Lake,1.2%,23.4%,12.9%,48.8%,0.9%,0.2%,1.4%,11.2%
Lakewood,1.0%,28.9%,14.8%,42.7%,0.3%,0.4%,0.7%,11.2%
Lynnwood,1.0%,25.6%,14.0%,46.4%,0.7%,0.3%,1.2%,10.9%
Puyallup Downtown,1.0%,26.3%,15.7%,42.1%,1.4%,0.3%,1.1%,12.1%
Puyallup South Hill,0.9%,25.7%,14.1%,47.4%,0.6%,0.2%,0.3%,10.7%
Redmond Downtown,1.5%,22.6%,14.0%,40.2%,1.5%,0.2%,1.4%,18.6%
Redmond-Overlake,1.5%,21.9%,12.6%,42.4%,0.7%,0.2%,1.8%,18.9%
Renton,1.3%,24.2%,13.6%,44.5%,1.0%,0.2%,2.0%,13.2%
SeaTac,1.5%,22.9%,14.3%,38.8%,1.2%,0.2%,5.0%,16.0%
Seattle Downtown,2.4%,11.1%,5.7%,17.4%,0.3%,1.6%,12.7%,49.0%
Seattle First Hill/Capitol Hill,3.2%,10.6%,5.4%,21.6%,0.4%,1.7%,9.6%,47.5%
Seattle Northgate,1.5%,19.7%,8.7%,39.9%,0.7%,0.3%,12.2%,16.9%
Seattle South Lake Union,2.7%,12.2%,5.5%,24.9%,0.2%,1.2%,9.1%,44.3%
Seattle University Community,3.7%,13.3%,7.1%,30.6%,0.5%,0.5%,14.8%,29.6%
Seattle Uptown,3.3%,13.1%,6.1%,28.7%,0.2%,0.9%,5.8%,41.8%
Silverdale,0.9%,26.7%,14.9%,45.7%,1.1%,0.2%,0.2%,10.3%
Tacoma Downtown,1.8%,19.1%,10.7%,36.7%,0.8%,0.4%,3.2%,27.3%
Tacoma Mall,1.6%,24.9%,12.9%,41.4%,0.9%,0.5%,1.4%,16.5%
Tukwila,0.9%,27.0%,14.4%,47.9%,0.1%,0.2%,2.9%,6.6%
University Place,1.5%,24.0%,12.8%,43.2%,1.3%,0.3%,0.8%,16.0%

:::

## mode share by tour destination

:::{.panel-tabset}

### RGC

\[TOUR\] Mode Share for All Purposes by Regional Center (Destination Location)

In [39]:
calc_mode_share_by_rgc(df_tour, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,Park,SOV,School Bus,TNC,Transit,Walk
tour_d_rgc,,,,,,,,,
Region,1.4%,22.1%,19.3%,0.1%,37.9%,2.6%,0.5%,3.2%,13.0%
In RGC,1.5%,18.4%,14.2%,0.5%,39.3%,0.6%,1.0%,8.0%,16.3%
Not in RGC,1.3%,23.2%,20.7%,0.1%,37.5%,3.1%,0.3%,1.9%,12.0%
Auburn,0.7%,25.2%,20.6%,0.1%,41.9%,0.3%,0.3%,2.4%,8.6%
Bellevue,1.3%,17.7%,14.4%,0.2%,42.8%,0.3%,0.7%,3.4%,19.1%
Bothell Canyon Park,0.8%,24.2%,21.7%,0.0%,45.0%,1.9%,0.4%,0.8%,5.0%
Bremerton,1.2%,20.9%,15.7%,0.5%,49.9%,0.1%,0.4%,0.8%,10.4%
Burien,0.8%,23.6%,18.3%,0.0%,40.1%,1.6%,0.3%,3.9%,11.3%
Everett,0.9%,22.8%,17.9%,0.1%,40.7%,1.0%,0.4%,2.4%,13.9%
Federal Way,0.7%,25.8%,19.0%,0.0%,42.3%,0.4%,0.2%,2.6%,8.9%
Greater Downtown Kirkland,1.0%,22.5%,17.8%,0.1%,43.6%,1.2%,0.3%,2.3%,11.2%
Issaquah,0.8%,24.1%,18.8%,0.1%,49.0%,0.8%,0.3%,0.9%,5.2%
Kent,0.7%,25.6%,21.9%,0.1%,39.2%,1.5%,0.3%,2.8%,7.9%
Kirkland Totem Lake,0.9%,22.3%,16.8%,0.1%,49.0%,0.9%,0.3%,2.1%,7.6%
Lakewood,0.8%,26.5%,19.4%,0.0%,43.1%,0.1%,0.5%,1.2%,8.5%
Lynnwood,0.9%,24.9%,18.2%,0.0%,46.2%,0.6%,0.4%,1.7%,7.0%
Puyallup Downtown,0.7%,26.4%,22.6%,0.1%,38.9%,2.7%,0.3%,1.3%,7.0%
Puyallup South Hill,0.7%,24.4%,18.8%,0.0%,47.7%,0.3%,0.3%,0.4%,7.6%
Redmond Downtown,0.9%,23.6%,20.6%,0.1%,36.8%,2.6%,0.3%,2.0%,13.3%
Redmond-Overlake,1.0%,19.0%,14.8%,0.2%,53.9%,0.3%,0.6%,1.6%,8.6%
Renton,0.8%,22.4%,19.3%,0.1%,46.2%,1.4%,0.4%,2.3%,7.1%
SeaTac,0.9%,20.6%,16.6%,0.4%,49.0%,0.4%,0.4%,3.7%,8.0%
Seattle Downtown,2.1%,11.8%,8.8%,1.4%,29.7%,0.3%,2.2%,18.7%,25.0%
Seattle First Hill/Capitol Hill,2.4%,13.7%,10.1%,0.5%,29.7%,0.6%,1.6%,11.8%,29.7%
Seattle Northgate,1.4%,19.8%,14.7%,0.1%,42.6%,1.1%,0.5%,7.1%,12.7%
Seattle South Lake Union,2.4%,13.6%,9.6%,0.6%,37.3%,0.1%,1.6%,10.1%,24.5%
Seattle University Community,2.7%,13.8%,10.5%,0.5%,37.3%,0.6%,0.6%,17.2%,16.8%
Seattle Uptown,2.4%,14.9%,10.6%,0.3%,33.7%,0.2%,1.0%,6.8%,30.2%
Silverdale,0.6%,26.3%,20.6%,0.0%,43.8%,1.7%,0.3%,0.2%,6.4%
Tacoma Downtown,1.3%,20.2%,15.8%,0.1%,44.3%,0.9%,0.5%,3.3%,13.6%
Tacoma Mall,1.2%,24.6%,17.7%,0.1%,44.4%,0.5%,0.5%,1.5%,9.6%
Tukwila,0.8%,24.6%,18.1%,0.1%,48.9%,0.0%,0.4%,3.7%,3.4%
University Place,1.1%,24.3%,18.0%,0.0%,41.2%,1.1%,0.4%,1.2%,12.5%

\[TOUR\] Mode Share to Work by Regional Center (Destination Location)

In [40]:
df_tour_work = df_tour[df_tour['pdpurp'] == 'Work'].copy()
calc_mode_share_by_rgc(df_tour_work, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,Park,SOV,TNC,Transit,Walk
tour_d_rgc,,,,,,,,
Region,1.4%,15.3%,12.5%,0.5%,62.2%,1.0%,2.7%,4.3%
In RGC,1.8%,13.9%,11.3%,1.1%,55.1%,1.8%,6.0%,8.8%
Not in RGC,1.2%,16.1%,13.1%,0.2%,66.0%,0.6%,1.0%,1.8%
Auburn,1.0%,16.7%,14.7%,0.2%,62.8%,0.5%,1.6%,2.4%
Bellevue,1.5%,15.3%,13.2%,0.4%,59.3%,1.0%,1.9%,7.4%
Bothell Canyon Park,1.0%,16.0%,12.6%,0.1%,68.7%,0.7%,0.3%,0.7%
Bremerton,0.9%,16.9%,13.6%,0.8%,64.4%,0.5%,1.2%,1.7%
Burien,1.2%,16.6%,13.2%,0.2%,63.8%,0.7%,1.5%,2.8%
Everett,1.2%,16.0%,12.9%,0.2%,63.6%,0.6%,0.5%,4.9%
Federal Way,1.3%,16.3%,13.5%,0.1%,65.2%,0.4%,0.8%,2.4%
Greater Downtown Kirkland,1.2%,15.7%,13.2%,0.2%,65.7%,0.6%,1.0%,2.4%
Issaquah,0.6%,16.7%,13.5%,0.2%,67.3%,0.5%,0.5%,0.9%
Kent,1.1%,17.2%,14.4%,0.6%,61.5%,0.8%,1.7%,2.7%
Kirkland Totem Lake,1.1%,15.9%,13.7%,0.2%,65.9%,0.6%,0.6%,2.0%
Lakewood,1.5%,15.1%,12.4%,0.1%,66.4%,0.5%,1.0%,2.9%
Lynnwood,1.4%,15.6%,13.2%,0.1%,66.2%,0.7%,0.5%,2.3%
Puyallup Downtown,0.8%,16.0%,13.3%,0.3%,65.1%,0.5%,2.0%,1.9%
Puyallup South Hill,0.6%,16.9%,13.8%,0.1%,65.9%,0.3%,0.5%,1.9%
Redmond Downtown,1.4%,15.5%,12.1%,0.2%,62.9%,0.7%,0.7%,6.5%
Redmond-Overlake,1.1%,15.6%,12.9%,0.3%,66.4%,0.8%,1.0%,1.9%
Renton,1.1%,16.4%,14.1%,0.2%,64.3%,0.7%,1.1%,2.2%
SeaTac,1.0%,16.6%,13.6%,0.6%,63.2%,0.6%,2.5%,1.8%
Seattle Downtown,2.4%,10.8%,8.6%,2.5%,42.6%,3.4%,14.2%,15.6%
Seattle First Hill/Capitol Hill,2.3%,12.8%,9.9%,1.2%,47.9%,2.7%,6.7%,16.5%
Seattle Northgate,2.2%,14.8%,12.2%,0.3%,62.7%,0.9%,2.4%,4.4%
Seattle South Lake Union,2.7%,12.9%,10.3%,1.0%,52.7%,2.6%,4.8%,13.0%
Seattle University Community,1.9%,15.0%,12.0%,1.2%,60.8%,1.2%,4.7%,3.1%
Seattle Uptown,2.7%,13.3%,10.2%,0.7%,53.2%,1.6%,3.1%,15.2%
Silverdale,1.1%,15.7%,12.1%,0.2%,67.1%,0.5%,0.3%,3.0%
Tacoma Downtown,1.7%,16.8%,13.5%,0.2%,60.9%,0.5%,1.8%,4.5%
Tacoma Mall,1.8%,15.3%,13.8%,0.2%,65.1%,0.7%,1.0%,2.1%
Tukwila,0.9%,16.6%,14.0%,0.2%,65.7%,0.7%,1.5%,0.4%
University Place,1.6%,16.1%,12.4%,0.2%,64.4%,0.5%,0.9%,4.0%

\[TOUR\] Mode Share for Non-work Purposes by Regional Center (Destination Location)

In [41]:
df_tour_non_work = df_tour[df_tour['pdpurp'] != 'Work'].copy()
calc_mode_share_by_rgc(df_tour_non_work, 'tour_d_rgc', 'tmodetp', 'toexpfac')

tmodetp,Bike,HOV2,HOV3+,SOV,School Bus,TNC,Transit,Walk
tour_d_rgc,,,,,,,,
Region,1.3%,24.7%,21.9%,28.6%,3.5%,0.2%,3.4%,16.3%
In RGC,1.3%,21.9%,16.5%,27.2%,1.1%,0.4%,9.5%,22.1%
Not in RGC,1.3%,25.3%,23.0%,28.9%,4.1%,0.2%,2.2%,15.1%
Auburn,0.6%,28.1%,22.6%,34.7%,0.4%,0.2%,2.6%,10.8%
Bellevue,1.0%,20.9%,16.1%,22.0%,0.7%,0.2%,5.2%,33.9%
Bothell Canyon Park,0.8%,29.5%,27.5%,30.0%,3.1%,0.2%,1.2%,7.8%
Bremerton,1.8%,27.2%,19.1%,27.3%,0.3%,0.3%,0.2%,23.9%
Burien,0.7%,25.0%,19.3%,35.5%,2.0%,0.2%,4.3%,13.0%
Everett,0.8%,25.7%,20.0%,30.9%,1.4%,0.3%,3.2%,17.7%
Federal Way,0.6%,28.4%,20.4%,36.1%,0.6%,0.2%,3.1%,10.6%
Greater Downtown Kirkland,0.9%,26.3%,20.2%,31.6%,1.9%,0.2%,3.0%,16.0%
Issaquah,1.0%,28.0%,21.5%,39.7%,1.2%,0.2%,1.1%,7.4%
Kent,0.5%,28.0%,24.0%,32.8%,1.9%,0.2%,3.2%,9.3%
Kirkland Totem Lake,0.8%,25.3%,18.2%,41.1%,1.3%,0.2%,2.8%,10.2%
Lakewood,0.6%,29.8%,21.4%,36.3%,0.1%,0.4%,1.3%,10.1%
Lynnwood,0.7%,28.2%,20.1%,39.0%,0.9%,0.2%,2.2%,8.7%
Puyallup Downtown,0.7%,28.8%,24.8%,32.9%,3.3%,0.3%,1.1%,8.2%
Puyallup South Hill,0.7%,26.4%,20.1%,42.7%,0.3%,0.3%,0.4%,9.1%
Redmond Downtown,0.7%,26.3%,23.4%,27.9%,3.5%,0.2%,2.4%,15.5%
Redmond-Overlake,0.8%,25.1%,18.4%,31.2%,0.7%,0.2%,2.8%,20.8%
Renton,0.7%,27.1%,23.2%,32.2%,2.5%,0.2%,3.2%,10.9%
SeaTac,0.8%,26.8%,21.0%,27.3%,0.9%,0.2%,5.5%,17.4%
Seattle Downtown,1.9%,13.3%,9.0%,11.8%,0.7%,0.6%,24.9%,37.9%
Seattle First Hill/Capitol Hill,2.5%,14.4%,10.2%,16.5%,1.0%,0.8%,15.5%,39.2%
Seattle Northgate,1.1%,22.4%,16.1%,32.1%,1.6%,0.2%,9.5%,16.9%
Seattle South Lake Union,2.1%,14.5%,8.8%,17.9%,0.3%,0.5%,16.8%,39.1%
Seattle University Community,3.2%,13.1%,9.5%,22.3%,1.0%,0.2%,25.2%,25.6%
Seattle Uptown,2.2%,16.0%,10.8%,19.2%,0.4%,0.6%,9.5%,41.4%
Silverdale,0.5%,28.9%,22.8%,38.0%,2.1%,0.3%,0.1%,7.3%
Tacoma Downtown,1.0%,23.3%,18.0%,28.9%,1.7%,0.4%,4.7%,22.0%
Tacoma Mall,1.0%,28.3%,19.2%,36.1%,0.7%,0.5%,1.7%,12.6%
Tukwila,0.7%,28.3%,19.9%,41.3%,0.0%,0.2%,4.7%,4.8%
University Place,1.0%,26.8%,19.6%,34.5%,1.4%,0.4%,1.3%,15.0%

:::