In [1]:
import os, sys, time, glob
import warnings
import re
warnings.simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import pandana as pdna
pd.options.mode.chained_assignment = None
import h5py
sys.path.append(os.path.join(os.getcwd(),r'..\..\..'))
# from input_configuration import base_year
import toml
config = toml.load(os.path.join(os.getcwd(),r'../../../configuration/input_configuration.toml'))

%matplotlib inline

from IPython.display import display, HTML

if (sys.version_info < (3, 0)):
    HTML('''<script>
    code_show=true; 
    function code_toggle() {
     if (code_show){
     $('div.input').hide();
     } else {
     $('div.input').show();
     }
     code_show = !code_show
    } 
    $( document ).ready(code_toggle);
    </script>
    <form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

In [2]:
CSS = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(CSS))

# Relative path between notebooks and goruped output directories
relative_path = '../../../outputs'
survey_path = '../../../inputs/base_year/survey'

# Write out CSVs with a numeric value prefix to help organize outputs 
incr = 1

In [3]:
pd.options.display.float_format = '{:0,.0f}'.format

In [4]:
def load_network_summary(filepath):
    """Load network-level results using a standard procedure. """
    df = pd.read_csv(filepath)

    # Congested network components by time of day
    df.columns

    # Get freeflow from 20to5 period

    # Exclude trips taken on non-designated facilities (facility_type == 0)
    # These are artificial (weave lanes to connect HOV) or for non-auto uses 
    df = df[df['data3'] != 0]    # data3 represents facility_type

    # calculate total link VMT and VHT
    df['VMT'] = df['@tveh']*df['length']
    df['VHT'] = df['@tveh']*df['auto_time']/60

    # Define facility type
    df.loc[df['data3'].isin([1,2]), 'facility_type'] = 'highway'
    df.loc[df['data3'].isin([3,4,6]), 'facility_type'] = 'arterial'
    df.loc[df['data3'].isin([5]), 'facility_type'] = 'connector'

    # Calculate delay
    # Select links from overnight time of day
    delay_df = df.loc[df['tod'] == '20to5'][['ij','auto_time']]
    delay_df.rename(columns={'auto_time':'freeflow_time'}, inplace=True)

    # Merge delay field back onto network link df
    df = pd.merge(df, delay_df, on='ij', how='left')

    # Calcualte hourly delay
    df['total_delay'] = ((df['auto_time']-df['freeflow_time'])*df['@tveh'])/60    # sum of (volume)*(travtime diff from freeflow)

    df['county'] =df['@countyid'].map({33: 'King',
                                      35: 'Kitsap',
                                      53: 'Pierce',
                                      61: 'Snohomish'})
    
    return df

In [5]:
output_dir = r'..\..\..\outputs\compare\RTP\person'

# Trips per Day by Resident
County, Center, Regional Geography

Youth, elderly, LEP, Race & Poverty for Region Work/Non-Work

In [6]:
pd.options.display.float_format = '{:0,.1f}'.format
df_trip = pd.read_csv(r'..\..\..\outputs\agg\dash\person_trips.csv')
df_person = pd.read_csv(r'..\..\..\outputs\agg\dash\person_geog.csv')

df_trip['is_rgc'] = 0
df_trip.loc[df_trip['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 1
df_person['is_rgc'] = 0
df_person.loc[df_person['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 1

In [7]:
test = pd.read_csv(r'R:\e2projects_two\SoundCast\Inputs\db_inputs\parcel_2018_geography.csv')

In [8]:
test['GrowthCenterName'].value_counts()

Not in RGC                                  1273792
Seattle First Hill/Capitol Hill                2883
Tacoma Downtown                                2868
Duwamish                                       2013
Everett                                        1964
Seattle University Community                   1401
Seattle Downtown                               1348
Kent MIC                                        873
Tacoma Mall                                     861
Burien                                          802
Ballard-Interbay                                797
Bremerton                                       779
Cascade                                         755
SeaTac                                          743
Port of Tacoma                                  732
Lakewood                                        699
Paine Field / Boeing Everett                    681
Renton                                          674
Puyallup Downtown                               668
Seattle Uptown                                  616
Auburn                                          560
Silverdale                                      531
University Place                                489
Sumner Pacific                                  488
Kent                                            439
Frederickson                                    436
Seattle South Lake Union                        406
Lynnwood                                        398
Redmond Downtown                                395
Seattle Northgate                               368
Bellevue                                        349
Kirkland Totem Lake                             291
Puyallup South Hill                             286
Tukwila                                         260
North Tukwila                                   180
Bothell Canyon Park                             170
Issaquah                                        147
Puget Sound Industrial Center- Bremerton        115
Redmond-Overlake                                113
Federal Way                                      64
Name: GrowthCenterName, dtype: int64

In [9]:
df_trip['hh_rgc'].unique()

array(['Not in RGC', 'Auburn', 'Bellevue', 'Bothell Canyon Park',
       'Bremerton', 'Burien', 'Everett', 'Federal Way',
       'Greater Downtown Kirkland', 'Kent', 'Kirkland Totem Lake',
       'Lakewood', 'Lynnwood', 'Puyallup Downtown', 'Puyallup South Hill',
       'Redmond Downtown', 'Redmond-Overlake', 'Renton', 'SeaTac',
       'Seattle Downtown', 'Seattle First Hill/Capitol Hill',
       'Seattle Northgate', 'Seattle South Lake Union',
       'Seattle University Community', 'Seattle Uptown',
       'Tacoma Downtown', 'Tacoma Mall', 'Tukwila', 'University Place'],
      dtype=object)

### County and Region

In [10]:
def trips_per_day(geog): 
    df1 = df_person.groupby(geog).sum()[['psexpfac']]
    df2 = df_trip.groupby(geog).sum()[['trexpfac']]
    df = df1.merge(df2, left_index=True, right_index=True)
    df.loc['Region', 'psexpfac'] = df_person.sum()['psexpfac']
    df.loc['Region', 'trexpfac'] = df_trip.sum()['trexpfac']
    df['Total Trips per Day'] = df['trexpfac']/df['psexpfac']

    df_trip.loc[df_trip['dpurp'] != 'Work', 'trip_type'] = 'Non-Work'
    df_trip.loc[df_trip['dpurp'] == 'Work', 'trip_type'] = 'Work'
    for purp in ['Work','Non-Work']:
        _df = df_trip[df_trip['trip_type'] == purp].groupby(geog).sum()[['trexpfac']]
        _df.rename(columns={'trexpfac': purp + ' Trips'}, inplace=True)

        # Add regional total to bottom of table
        _df.loc['Region', purp + ' Trips'] = df_trip[df_trip['trip_type'] == purp].sum()['trexpfac']
        df = df.merge(_df, left_index=True, right_index=True)

    df['Work Trips per Day'] = df['Work Trips']/df['psexpfac']
    df['Non-Work Trips per Day'] = df['Non-Work Trips']/df['psexpfac']
    df[['Work Trips per Day','Non-Work Trips per Day','Total Trips per Day']]
    
    return df[['Work Trips per Day', 'Non-Work Trips per Day','Total Trips per Day']]

In [11]:
df = trips_per_day('hh_county')
df.to_csv(os.path.join(output_dir,str(incr)+'_trips_per_day_county.csv')); incr+=1
df

           Work Trips per Day  Non-Work Trips per Day  Total Trips per Day
hh_county
King                      0.7                     3.3                  4.0
Kitsap                    0.5                     3.3                  3.9
Pierce                    0.6                     3.3                  3.9
Snohomish                 0.6                     3.3                  3.9
Region                    0.7                     3.3                  4.0

### Regional Growth Centers

In [12]:
df = trips_per_day('is_rgc')
# df.index = ['Not in RGC', 'In RGC','Region']
df

        Work Trips per Day  Non-Work Trips per Day  Total Trips per Day
is_rgc
0                      0.6                     3.3                  3.9
1                      0.8                     3.2                  4.0
Region                 0.7                     3.3                  4.0

In [13]:
df = trips_per_day('hh_rgc')
df.to_csv(os.path.join(output_dir,str(incr)+'_trips_per_day_rgc.csv')); incr+=1
df

,Work Trips per Day,Non-Work Trips per Day,Total Trips per Day
hh_rgc,,,
Auburn,0.6,3.4,4.0
Bellevue,0.8,3.4,4.2
Bothell Canyon Park,0.8,3.3,4.1
Bremerton,0.7,3.5,4.2
Burien,0.7,3.2,4.0
Everett,0.7,3.4,4.0
Federal Way,0.6,3.7,4.3
Greater Downtown Kirkland,0.7,3.2,3.9
Kent,0.5,3.4,3.9
Kirkland Totem Lake,0.7,3.3,4.0
Lakewood,0.6,3.5,4.1
Lynnwood,0.7,3.4,4.1
Not in RGC,0.6,3.3,3.9
Puyallup Downtown,0.6,3.4,3.9
Puyallup South Hill,0.7,3.1,3.8
Redmond Downtown,0.8,3.3,4.1
Redmond-Overlake,0.8,3.3,4.1
Renton,0.7,3.3,4.0
SeaTac,0.6,3.3,4.0
Seattle Downtown,1.0,3.3,4.3
Seattle First Hill/Capitol Hill,1.0,3.2,4.2
Seattle Northgate,0.7,3.2,3.9
Seattle South Lake Union,1.0,3.2,4.2
Seattle University Community,0.6,2.6,3.2
Seattle Uptown,1.0,3.2,4.2
Tacoma Downtown,0.6,3.4,4.0
Tacoma Mall,0.6,3.3,3.8
Tukwila,1.0,3.1,4.1
University Place,0.6,3.3,3.9
Region,0.7,3.3,4.0

### Regional Geographies

In [14]:
df = trips_per_day('hh_rg_proposed')
df.to_csv(os.path.join(output_dir,str(incr)+'_trips_per_day_reg_geog.csv')); incr+=1
df

,Work Trips per Day,Non-Work Trips per Day,Total Trips per Day
hh_rg_proposed,,,
Auburn,0.6,3.4,4.0
Bellevue,0.8,3.4,4.2
Bothell Canyon Park,0.8,3.3,4.1
Bremerton,0.7,3.5,4.2
Burien,0.7,3.2,4.0
Everett,0.7,3.4,4.0
Federal Way,0.6,3.7,4.3
Greater Downtown Kirkland,0.7,3.2,3.9
Kent,0.5,3.4,3.9
Kirkland Totem Lake,0.7,3.3,4.0
Lakewood,0.6,3.5,4.1
Lynnwood,0.7,3.4,4.1
Not in RGC,0.6,3.3,3.9
Puyallup Downtown,0.6,3.4,3.9
Puyallup South Hill,0.7,3.1,3.8
Redmond Downtown,0.8,3.3,4.1
Redmond-Overlake,0.8,3.3,4.1
Renton,0.7,3.3,4.0
SeaTac,0.6,3.3,4.0
Seattle Downtown,1.0,3.3,4.3
Seattle First Hill/Capitol Hill,1.0,3.2,4.2
Seattle Northgate,0.7,3.2,3.9
Seattle South Lake Union,1.0,3.2,4.2
Seattle University Community,0.6,2.6,3.2
Seattle Uptown,1.0,3.2,4.2
Tacoma Downtown,0.6,3.4,4.0
Tacoma Mall,0.6,3.3,3.8
Tukwila,1.0,3.1,4.1
University Place,0.6,3.3,3.9
Region,0.7,3.3,4.0

### Equity Geographies

In [15]:
# Summary by equity geographies
# Calculate person totals
results_df = pd.DataFrame()
trip_rate_df = pd.DataFrame()
list_50 = ['hh_racial','hh_poverty']

equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        val = df_person[df_person[equity_geog+geog_type] == 1].sum()['psexpfac']
        results_df.loc[equity_geog+geog_type,'psexpfac'] = val
        
# Calculate total work trips per each group
work_results_df = pd.DataFrame()
equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        for purp in ['Non-Work','Work']:
            _df = df_trip[df_trip['trip_type'] == purp].groupby(equity_geog+geog_type).sum()[['trexpfac']]
            if 1 in _df.index:
                if geog_type == '_reg' or equity_geog in list_50:
                    _rate_df = pd.DataFrame([purp,
                                         equity_geog+geog_type,
                                         _df.loc[1].trexpfac/results_df.loc[equity_geog+geog_type].psexpfac]).T
                trip_rate_df = trip_rate_df.append(_rate_df) 
trip_rate_df.columns = ['Trip Type','Equity Group','Trip Rate']
df = trip_rate_df.pivot_table(columns='Trip Type', index='Equity Group', values='Trip Rate', aggfunc='sum')
df['Total Trips per Day'] = df['Non-Work'] + df['Work']
df.rename(columns={'Non-Work': 'Non-Work Trips per Day', 'Work': 'Work Trips per Day'}, inplace=True)
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df.to_csv(os.path.join(output_dir,str(incr)+'_trips_per_day_equity.csv'))
HTML(df[['Equity Group','Work Trips per Day','Non-Work Trips per Day','Total Trips per Day']].to_html(index=False))

In [16]:
# Summary by equity geographies
# Calculate person totals
results_df = pd.DataFrame()
trip_rate_df = pd.DataFrame()
list_50 = ['hh_racial','hh_poverty']

equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        val = df_person[df_person[equity_geog+geog_type] == 0].sum()['psexpfac']
        results_df.loc[equity_geog+geog_type,'psexpfac'] = val
        
# Calculate total work trips per each group
work_results_df = pd.DataFrame()
equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        for purp in ['Non-Work','Work']:
            _df = df_trip[df_trip['trip_type'] == purp].groupby(equity_geog+geog_type).sum()[['trexpfac']]
            if 1 in _df.index:
                if geog_type == '_reg' or equity_geog in list_50:
                    _rate_df = pd.DataFrame([purp,
                                         equity_geog+geog_type,
                                         _df.loc[1].trexpfac/results_df.loc[equity_geog+geog_type].psexpfac]).T
                trip_rate_df = trip_rate_df.append(_rate_df) 
trip_rate_df.columns = ['Trip Type','Equity Group','Trip Rate']
df = trip_rate_df.pivot_table(columns='Trip Type', index='Equity Group', values='Trip Rate', aggfunc='sum')
df['Total Trips per Day'] = df['Non-Work'] + df['Work']

df.rename(columns={'Non-Work': 'Non-Work Trips per Day', 'Work': 'Work Trips per Day'}, inplace=True)
df = df.reset_index()
df = df.rename_axis(None, axis=1)
df['Equity Group'] = ['NOT in '+i for i in df['Equity Group']]
df.to_csv(os.path.join(output_dir,str(incr)+'_trips_per_day_equity.csv'))
HTML(df[['Equity Group','Work Trips per Day','Non-Work Trips per Day','Total Trips per Day']].to_html(index=False))

# Miles Driven per Day by Resident
County, Center, Regional Geography

Youth, elderly, LEP, Race & Poverty for Region Work/Non-Work

In [17]:
pd.options.display.float_format = '{:0,.1f}'.format
df_vmt = pd.read_csv(r'..\..\..\outputs\agg\dash\person_vmt.csv')
df_person = pd.read_csv(r'..\..\..\outputs\agg\dash\person_geog.csv')

df_vmt['is_rgc'] = 0
df_vmt.loc[df_vmt['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 1
df_person['is_rgc'] = 0
df_person.loc[df_person['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 1

# Select only drivers (dorp = 1) and auto trips
df_vmt = df_vmt[df_vmt['mode'].isin(['SOV','HOV2','HOV3+']) & (df_vmt['dorp'] == 1)]

def vmt_per_person(df_vmt, df_person, geog):
    _df_vmt = df_vmt.groupby(geog).sum()[['travdist_wt']]
    _df_person = df_person.groupby(geog).sum()[['psexpfac']]

    df = _df_vmt.merge(_df_person, left_index=True, right_index=True)
    df.loc['Region',:] = df.sum(axis=0)
    df['Average Miles per Person'] = df['travdist_wt']/df['psexpfac']
    
    return df[['Average Miles per Person']]

### County

In [18]:
df = vmt_per_person(df_vmt, df_person, 'hh_county')
df.to_csv(os.path.join(output_dir,str(incr)+'_vmt_county.csv')); incr+=1
df

           Average Miles per Person
hh_county
King                           13.6
Kitsap                         10.0
Pierce                         13.8
Snohomish                      15.0
Region                         13.7

### Regional Growth Centers

In [19]:
df = vmt_per_person(df_vmt, df_person, 'is_rgc')
df.index = ['Not in RGC', 'In RGC','Region']
df

            Average Miles per Person
Not in RGC                      14.3
In RGC                           8.2
Region                          13.7

In [20]:
df = vmt_per_person(df_vmt, df_person, 'hh_rgc')
df.to_csv(os.path.join(output_dir,str(incr)+'_vmt_rgc.csv')); incr+=1
df

                                 Average Miles per Person
hh_rgc
Auburn                                               14.2
Bellevue                                             10.3
Bothell Canyon Park                                  15.0
Bremerton                                             8.8
Burien                                               13.7
Everett                                              13.1
Federal Way                                          12.8
Greater Downtown Kirkland                            15.2
Kent                                                 12.0
Kirkland Totem Lake                                  15.7
Lakewood                                             11.8
Lynnwood                                             13.2
Not in RGC                                           14.3
Puyallup Downtown                                    11.9
Puyallup South Hill                                  13.4
Redmond Downtown                                     13.5
Redmond-Overlake                                     12.4
Renton                                               13.0
SeaTac                                               12.5
Seattle Downtown                                      3.4
Seattle First Hill/Capitol Hill                       4.4
Seattle Northgate                                    11.5
Seattle South Lake Union                              5.0
Seattle University Community                          7.0
Seattle Uptown                                        6.8
Tacoma Downtown                                       8.9
Tacoma Mall                                          10.2
Tukwila                                              14.1
University Place                                     11.5
Region                                               13.7

### Regional Geography

In [21]:
df = vmt_per_person(df_vmt, df_person, 'hh_rg_proposed')
df.to_csv(os.path.join(output_dir,str(incr)+'_vmt_reg_geog.csv')); incr+=1
df

                                 Average Miles per Person
hh_rg_proposed
Auburn                                               14.2
Bellevue                                             10.3
Bothell Canyon Park                                  15.0
Bremerton                                             8.8
Burien                                               13.7
Everett                                              13.1
Federal Way                                          12.8
Greater Downtown Kirkland                            15.2
Kent                                                 12.0
Kirkland Totem Lake                                  15.7
Lakewood                                             11.8
Lynnwood                                             13.2
Not in RGC                                           14.3
Puyallup Downtown                                    11.9
Puyallup South Hill                                  13.4
Redmond Downtown                                     13.5
Redmond-Overlake                                     12.4
Renton                                               13.0
SeaTac                                               12.5
Seattle Downtown                                      3.4
Seattle First Hill/Capitol Hill                       4.4
Seattle Northgate                                    11.5
Seattle South Lake Union                              5.0
Seattle University Community                          7.0
Seattle Uptown                                        6.8
Tacoma Downtown                                       8.9
Tacoma Mall                                          10.2
Tukwila                                              14.1
University Place                                     11.5
Region                                               13.7

### Equity Geographies
Average Miles per Person (by residence inside or outside equity geography)

In [22]:
result_df = pd.DataFrame()
list_50 = ['hh_racial','hh_poverty']
equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        if geog_type == '_reg' or equity_geog in list_50:
            col = equity_geog+geog_type
            df = vmt_per_person(df_vmt, df_person, col)
            if 1 in df.index:
                df = df.loc[1]
            df['source'] = col
            result_df = result_df.append(df)
result_df.index = result_df.source
result_df.drop('source', axis=1, inplace=True)
result_df = result_df[~result_df.index.duplicated()]
df_in = result_df.copy()

result_df = pd.DataFrame()
list_50 = ['hh_racial','hh_poverty']
equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        if geog_type == '_reg' or equity_geog in list_50:
            col = equity_geog+geog_type
            df = vmt_per_person(df_vmt, df_person, col)
            if 0 in df.index:
                df = df.loc[0]
            df['source'] = col
            result_df = result_df.append(df)
result_df.index = result_df.source
result_df.drop('source', axis=1, inplace=True)
result_df = result_df[~result_df.index.duplicated()]
# result_df.index = ['NOT in '+i for i in result_df.index]


df_out = result_df.copy()

df = df_in.merge(df_out, left_index=True, right_index=True)
df.columns = ['Inside Equity Geography',  'Outside Equity Geography']
df.to_csv(os.path.join(output_dir,str(incr)+'_vmt_equity.csv')); incr+=1
df

                   Inside Equity Geography  Outside Equity Geography
source
hh_youth_reg                          15.1                      12.6
hh_elderly_reg                        13.7                      13.7
hh_english_reg                        13.7                      13.7
hh_racial_reg                         13.5                      13.9
hh_racial_50                          13.6                      13.8
hh_poverty_reg                        12.8                      14.3
hh_poverty_50                         10.1                      13.8
hh_disability_reg                     13.3                      14.0

# Miles Walking and Biking per Day by Resident
County, Center, Regional Geography

Youth, elderly, LEP, Race & Poverty for Region Work/Non-Work

In [23]:
df_vht = pd.read_csv(r'..\..\..\outputs\agg\dash\person_vht.csv')
df_hh = pd.read_csv(r'..\..\..\outputs\agg\dash\hh_geog.csv')



def walk_bike_per_person_time(df_vmt, df_person, geog):
    
    results_df = pd.DataFrame()
    for mode in ['Walk','Bike']:
        
        _df_vmt = df_vmt[df_vmt['mode'] == mode]
        _df_vmt = _df_vmt.groupby(geog).sum()[['travtime_wt']]
        _df_hh = df_hh.groupby(geog).sum()[['hhexpfac']]

        df = _df_vmt.merge(_df_hh, left_index=True, right_index=True)
        df.loc['Region',:] = df.sum(axis=0)
        df['Average Miles per Person'] = df['travtime_wt']/df['hhexpfac']
        results_df[mode] = df['Average Miles per Person']
    
    _df_vmt = df_vmt[df_vmt['mode'].isin(['Walk','Bike'])]
    _df_vmt = _df_vmt.groupby(geog).sum()[['travtime_wt']]
    _df_hh = df_hh.groupby(geog).sum()[['hhexpfac']]

    df = _df_vmt.merge(_df_hh, left_index=True, right_index=True)
    df.loc['Region',:] = df.sum(axis=0)
    df['Average Miles per Person'] = df['travtime_wt']/df['hhexpfac']
    results_df['Walk and Bike'] = df['Average Miles per Person']
    
    return results_df

df = walk_bike_per_person_time(df_vht, df_hh, 'hh_county')
# df.to_csv(os.path.join(output_dir,str(incr)+'_mile_bikewalk_county.csv')); incr+=1
df

           Walk  Bike  Walk and Bike
hh_county
King       22.6   3.3           25.9
Kitsap     22.9   2.5           25.4
Pierce     21.3   3.4           24.7
Snohomish  21.0   3.3           24.3
Region     22.2   3.3           25.5

In [24]:
# df = pd.read_csv(r'..\..\..\outputs\agg\dash\trip_distance.csv')
# _df = df[df['mode'] == 'Bike']
# (_df['travdist_bin']*_df['trexpfac']).sum()/_df['trexpfac'].sum()

In [25]:
# _df = df[df['mode'] == 'Walk']
# (_df['travdist_bin']*_df['trexpfac']).sum()/_df['trexpfac'].sum()

In [26]:
df_vmt = pd.read_csv(r'..\..\..\outputs\agg\dash\person_vmt.csv')
df_person = pd.read_csv(r'..\..\..\outputs\agg\dash\person_geog.csv')

df_vmt['is_rgc'] = 0
df_vmt.loc[df_vmt['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 1
df_person['is_rgc'] = 0
df_person.loc[df_person['hh_rgc'] != 'Not in RGC', 'is_rgc'] = 1


def walk_bike_per_person(df_vmt, df_person, geog):
    
    results_df = pd.DataFrame()
    for mode in ['Walk','Bike']:
        
        _df_vmt = df_vmt[df_vmt['mode'] == mode]
        _df_vmt = _df_vmt.groupby(geog).sum()[['travdist_wt']]
        _df_person = df_person.groupby(geog).sum()[['psexpfac']]

        df = _df_vmt.merge(_df_person, left_index=True, right_index=True)
        df.loc['Region',:] = df.sum(axis=0)
        df['Average Miles per Person'] = df['travdist_wt']/df['psexpfac']
        results_df[mode] = df['Average Miles per Person']
    
    _df_vmt = df_vmt[df_vmt['mode'].isin(['Walk','Bike'])]
    _df_vmt = _df_vmt.groupby(geog).sum()[['travdist_wt']]
    _df_person = df_person.groupby(geog).sum()[['psexpfac']]

    df = _df_vmt.merge(_df_person, left_index=True, right_index=True)
    df.loc['Region',:] = df.sum(axis=0)
    df['Average Miles per Person'] = df['travdist_wt']/df['psexpfac']
    results_df['Walk and Bike'] = df['Average Miles per Person']
    
    return results_df

### County

In [27]:
df = walk_bike_per_person(df_vmt, df_person, 'hh_county')
df.to_csv(os.path.join(output_dir,str(incr)+'_mile_bikewalk_county.csv')); incr+=1
df

           Walk  Bike  Walk and Bike
hh_county
King        0.5   0.2            0.7
Kitsap      0.5   0.2            0.6
Pierce      0.4   0.2            0.6
Snohomish   0.4   0.2            0.6
Region      0.5   0.2            0.7

### Regional Growth Center

In [28]:
df = walk_bike_per_person(df_vmt, df_person, 'is_rgc')
df.index = ['Not in RGC', 'Inside RGC', 'Region']
df

            Walk  Bike  Walk and Bike
Not in RGC   0.4   0.2            0.6
Inside RGC   0.9   0.3            1.2
Region       0.5   0.2            0.7

In [29]:
df = walk_bike_per_person(df_vmt, df_person, 'hh_rgc')
df.to_csv(os.path.join(output_dir,str(incr)+'_mile_bikewalk_rgc.csv'))
df

                                 Walk  Bike  Walk and Bike
hh_rgc
Auburn                            0.4   0.4            0.9
Bellevue                          0.7   0.3            1.0
Bothell Canyon Park               0.4   0.1            0.5
Bremerton                         0.7   0.3            1.0
Burien                            0.5   0.3            0.7
Everett                           0.7   0.5            1.2
Federal Way                       0.7   0.5            1.3
Greater Downtown Kirkland         0.4   0.3            0.7
Kent                              0.5   0.4            0.8
Kirkland Totem Lake               0.4   0.3            0.7
Lakewood                          0.5   0.4            0.9
Lynnwood                          0.5   0.3            0.8
Not in RGC                        0.4   0.2            0.6
Puyallup Downtown                 0.5   0.3            0.8
Puyallup South Hill               0.5   0.3            0.7
Redmond Downtown                  0.6   0.3            0.9
Redmond-Overlake                  0.6   0.3            0.9
Renton                            0.5   0.3            0.8
SeaTac                            0.4   0.3            0.7
Seattle Downtown                  1.3   0.2            1.5
Seattle First Hill/Capitol Hill   1.3   0.2            1.5
Seattle Northgate                 0.6   0.4            1.0
Seattle South Lake Union          1.2   0.3            1.4
Seattle University Community      0.8   0.3            1.1
Seattle Uptown                    1.0   0.3            1.3
Tacoma Downtown                   0.8   0.4            1.2
Tacoma Mall                       0.7   0.4            1.1
Tukwila                           0.5   0.2            0.7
University Place                  0.5   0.2            0.7
Region                            0.5   0.2            0.7

### Regional Geography

In [30]:
df = walk_bike_per_person(df_vmt, df_person, 'hh_rg_proposed')
df.to_csv(os.path.join(output_dir,str(incr)+'_mile_bikewalk_reg_geog.csv')); incr+=1
df

                                 Walk  Bike  Walk and Bike
hh_rg_proposed
Auburn                            0.4   0.4            0.9
Bellevue                          0.7   0.3            1.0
Bothell Canyon Park               0.4   0.1            0.5
Bremerton                         0.7   0.3            1.0
Burien                            0.5   0.3            0.7
Everett                           0.7   0.5            1.2
Federal Way                       0.7   0.5            1.3
Greater Downtown Kirkland         0.4   0.3            0.7
Kent                              0.5   0.4            0.8
Kirkland Totem Lake               0.4   0.3            0.7
Lakewood                          0.5   0.4            0.9
Lynnwood                          0.5   0.3            0.8
Not in RGC                        0.4   0.2            0.6
Puyallup Downtown                 0.5   0.3            0.8
Puyallup South Hill               0.5   0.3            0.7
Redmond Downtown                  0.6   0.3            0.9
Redmond-Overlake                  0.6   0.3            0.9
Renton                            0.5   0.3            0.8
SeaTac                            0.4   0.3            0.7
Seattle Downtown                  1.3   0.2            1.5
Seattle First Hill/Capitol Hill   1.3   0.2            1.5
Seattle Northgate                 0.6   0.4            1.0
Seattle South Lake Union          1.2   0.3            1.4
Seattle University Community      0.8   0.3            1.1
Seattle Uptown                    1.0   0.3            1.3
Tacoma Downtown                   0.8   0.4            1.2
Tacoma Mall                       0.7   0.4            1.1
Tukwila                           0.5   0.2            0.7
University Place                  0.5   0.2            0.7
Region                            0.5   0.2            0.7

### Equity Geographies

In [31]:
result_df = pd.DataFrame()
equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        if geog_type == '_reg' or equity_geog in list_50:
            col = equity_geog+geog_type
            df = walk_bike_per_person(df_vmt, df_person, col)
            if 1 in df.index:
                df = df.loc[1]
            df['source'] = col
            result_df = result_df.append(df)
result_df.index = result_df.source
result_df.drop('source', axis=1, inplace=True)
result_df.to_csv(os.path.join(output_dir,str(incr)+'_mile_bikewalk_equity.csv')); incr+=1
result_df

                   Bike  Walk  Walk and Bike
source
hh_youth_reg        0.2   0.4            0.6
hh_elderly_reg      0.2   0.4            0.6
hh_english_reg      0.2   0.5            0.7
hh_english_reg      0.2   0.5            0.7
hh_racial_reg       0.2   0.5            0.7
hh_racial_50        0.2   0.5            0.7
hh_poverty_reg      0.2   0.5            0.7
hh_poverty_50       0.3   0.6            0.9
hh_disability_reg   0.2   0.5            0.7

In [32]:
result_df = pd.DataFrame()
equity_geogs = ['hh_youth','hh_elderly','hh_english','hh_racial','hh_poverty','hh_disability']
for equity_geog in equity_geogs:
    for geog_type in ['_reg','_50']:
        if geog_type == '_reg' or equity_geog in list_50:
            col = equity_geog+geog_type
            df = walk_bike_per_person(df_vmt, df_person, col)
            if 0 in df.index:
                df = df.loc[0]
            df['source'] = col
            result_df = result_df.append(df)
result_df.index = result_df.source
result_df.drop('source', axis=1, inplace=True)
result_df.index = ['NOT in '+i for i in result_df.index]
result_df.to_csv(os.path.join(output_dir,str(incr)+'_mile_bikewalk_equity.csv')); incr+=1
result_df

                          Bike  Walk  Walk and Bike
NOT in hh_youth_reg        0.2   0.5            0.7
NOT in hh_elderly_reg      0.2   0.5            0.7
NOT in hh_english_reg      0.2   0.5            0.7
NOT in hh_racial_reg       0.2   0.4            0.6
NOT in hh_racial_50        0.2   0.5            0.6
NOT in hh_poverty_reg      0.2   0.4            0.6
NOT in hh_poverty_50       0.2   0.5            0.7
NOT in hh_disability_reg   0.2   0.4            0.6

# Jobs Accessible within 45 Minutes of Transit

In [33]:
pd.options.display.float_format = '{:0,.0f}'.format
df = pd.read_csv(r'..\..\..\outputs\access\transit_jobs_access.csv'); incr+=1
df_lu = pd.read_csv(r'..\..\..\outputs\landuse\parcels_urbansim.txt',
                   sep='\s+', usecols=['parcelid','emptot_p'])
tot_jobs = df_lu['emptot_p'].sum()

### Region

In [34]:
_df = df[df['geography_group'] == 'region']
_df.index = _df.geography
_df = _df[['value']]
_df.rename(columns={'value': 'Jobs within 45-minute Transit Commute'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_transit_jobs_45min_region.csv')); incr+=1
_df['% Total Jobs'] = _df['Jobs within 45-minute Transit Commute']/tot_jobs
output = _df.to_html(formatters={
    '% Total Jobs': '{:0,.1%}'.format
}, index=False)
display(HTML(output))

### County

In [35]:
_df = df[df['geography_group'] == 'CountyName']
_df.index = _df.geography
_df = _df[['value']]
_df.rename(columns={'value': 'Jobs within 45-minute Transit Commute'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_transit_jobs_45min_county.csv')); incr+=1
_df['% Total Jobs'] = _df['Jobs within 45-minute Transit Commute']/tot_jobs
output = _df.to_html(formatters={
    '% Total Jobs': '{:0,.1%}'.format
})
display(HTML(output))

### Regional Growth Center

In [36]:
_df = df[df['geography_group'] == 'GrowthCenterName']
_df.index = _df.geography
_df = _df[['value']]
_df.rename(columns={'value': 'Jobs within 45-minute Transit Commute'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_transit_jobs_45min_rgc.csv')); incr+=1
_df['% Total Jobs'] = _df['Jobs within 45-minute Transit Commute']/tot_jobs
output = _df.to_html(formatters={
    '% Total Jobs': '{:0,.1%}'.format
})
display(HTML(output))

### Regional Geography

In [37]:
_df = df[df['geography_group'] == 'rg_proposed']
_df.index = _df.geography
_df = _df[['value']]
_df.rename(columns={'value': 'Jobs within 45-minute Transit Commute'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_transit_jobs_45min_reg_geog.csv')); incr+=1
_df['% Total Jobs'] = _df['Jobs within 45-minute Transit Commute']/tot_jobs
output = _df.to_html(formatters={
    '% Total Jobs': '{:0,.1%}'.format
})
display(HTML(output))

### Equity Geographies

In [38]:
geo_list = []
equity_geogs = ['youth','elderly','english','racial','poverty','disability']
for equity_geog in equity_geogs:
    for geog_type in ['_geog_vs_reg_total','_geog_vs_50_percent']:
        if geog_type == '_geog_vs_reg_total' or equity_geog in ['poverty','racial']:
            geo_list.append(equity_geog+geog_type)

In [39]:
result_df = pd.DataFrame()
for col in geo_list:
    _df = df[(df['geography_group'] == col) & (df['geography'] == '1')]
    result_df = result_df.append(_df[['geography_group', 'value']])
result_df.to_csv(os.path.join(output_dir,str(incr)+'_transit_jobs_45min_equity.csv')); incr+=1
result_df.rename(columns={'geography_group': 'Equity Group', 'value': 'Jobs within 45-minute Transit Commute'}, inplace=True)
# result_df = result_df['']
result_df['% Total Jobs'] = result_df['Jobs within 45-minute Transit Commute']/tot_jobs
output = result_df.to_html(formatters={
    '% Total Jobs': '{:0,.1%}'.format
}, index=False)
display(HTML(output))

In [40]:
result_df = pd.DataFrame()
for col in geo_list:
    _df = df[(df['geography_group'] == col) & (df['geography'] == '0')]
    result_df = result_df.append(_df[['geography_group', 'value']])
result_df.to_csv(os.path.join(output_dir,str(incr)+'_transit_jobs_45min_equity.csv')); incr+=1
result_df.rename(columns={'geography_group': 'Equity Group', 'value': 'Jobs within 45-minute Transit Commute'}, inplace=True)
# result_df = result_df['']
result_df['% Total Jobs'] = result_df['Jobs within 45-minute Transit Commute']/tot_jobs
result_df['Equity Group'] = ['NOT in '+i for i in result_df['Equity Group']]
output = result_df.to_html(formatters={
    '% Total Jobs': '{:0,.1%}'.format
}, index=False)
display(HTML(output))

# Average Jobs Accessible within 1 Mile Walk and 3 Mile Bike
Note that this is not using the bike network, but is instead using the all-streets network.
Average accessible jobs are weighted averages based on parcel household population.

In [41]:
df = pd.read_csv(r'..\..\..\outputs\access\walk_bike_jobs_access.csv')

### Regional Average

In [42]:
_df = df[df['geography_group'] == 'region']
_df.index = _df.geography_value
_df = _df[['jobs_1_mile_walk','jobs_3_mile_bike']]
_df.rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                   'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}, inplace=True)
_df['% Total Jobs (1-mile walk)'] = _df['Jobs within 1-mile Walk']/tot_jobs
_df['% Total Jobs (3-mile bike)'] = _df['Jobs within 3-mile Bike']/tot_jobs
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_region.csv')); incr+=1
output = _df.to_html(formatters={
    '% Total Jobs (1-mile walk)': '{:0,.1%}'.format,
    '% Total Jobs (3-mile bike)': '{:0,.1%}'.format,
}, index=False)
display(HTML(output))

### Home County

In [43]:
_df = df[df['geography_group'] == 'CountyName']
_df.index = _df.geography_value
_df = _df[['jobs_1_mile_walk','jobs_3_mile_bike']]
_df.rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                   'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_county.csv')); incr+=1
_df['% Total Jobs (1-mile walk)'] = _df['Jobs within 1-mile Walk']/tot_jobs
_df['% Total Jobs (3-mile bike)'] = _df['Jobs within 3-mile Bike']/tot_jobs
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_region.csv')); incr+=1
output = _df.to_html(formatters={
    '% Total Jobs (1-mile walk)': '{:0,.1%}'.format,
    '% Total Jobs (3-mile bike)': '{:0,.1%}'.format,
})
display(HTML(output))

### Regional Growth Center

In [44]:
_df = df[df['geography_group'] == 'GrowthCenterName']
_df.index = _df.geography_value
_df = _df[['jobs_1_mile_walk','jobs_3_mile_bike']]
_df.rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                   'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_rgc.csv')); incr+=1
_df['% Total Jobs (1-mile walk)'] = _df['Jobs within 1-mile Walk']/tot_jobs
_df['% Total Jobs (3-mile bike)'] = _df['Jobs within 3-mile Bike']/tot_jobs
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_region.csv')); incr+=1
output = _df.to_html(formatters={
    '% Total Jobs (1-mile walk)': '{:0,.1%}'.format,
    '% Total Jobs (3-mile bike)': '{:0,.1%}'.format,
})
display(HTML(output))

### Regional Geography

In [45]:
_df = df[df['geography_group'] == 'rg_proposed']
_df.index = _df.geography_value
_df = _df[['jobs_1_mile_walk','jobs_3_mile_bike']]
_df.rename(columns={'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                   'jobs_3_mile_bike': 'Jobs within 3-mile Bike'}, inplace=True)
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_reg_geog.csv')); incr+=1
_df['% Total Jobs (1-mile walk)'] = _df['Jobs within 1-mile Walk']/tot_jobs
_df['% Total Jobs (3-mile bike)'] = _df['Jobs within 3-mile Bike']/tot_jobs
_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_region.csv')); incr+=1
output = _df.to_html(formatters={
    '% Total Jobs (1-mile walk)': '{:0,.1%}'.format,
    '% Total Jobs (3-mile bike)': '{:0,.1%}'.format,
})
display(HTML(output))

### Equity Geographies

In [46]:
result_df = pd.DataFrame()
for col in geo_list:
    _df = df[(df['geography_group'] == col) & (df['geography_value'] == '1')]
    result_df = result_df.append(_df[['geography_group', 'jobs_1_mile_walk','jobs_3_mile_bike']])
result_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_equity.csv')); incr+=1
result_df.rename(columns={'geography_group': 'Equity Group', 
                          'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                        'jobs_3_mile_bike':  'Jobs within 3-mile Bike'}, inplace=True)

result_df['% Total Jobs (1-mile walk)'] = result_df['Jobs within 1-mile Walk']/tot_jobs
result_df['% Total Jobs (3-mile bike)'] = result_df['Jobs within 3-mile Bike']/tot_jobs
output = result_df.to_html(formatters={
    '% Total Jobs (1-mile walk)': '{:0,.1%}'.format,
    '% Total Jobs (3-mile bike)': '{:0,.1%}'.format
}, index=False)
display(HTML(output))

In [47]:
result_df = pd.DataFrame()
for col in geo_list:
    _df = df[(df['geography_group'] == col) & (df['geography_value'] == '0')]
    result_df = result_df.append(_df[['geography_group', 'jobs_1_mile_walk','jobs_3_mile_bike']])
result_df.to_csv(os.path.join(output_dir,str(incr)+'_walk_bike_jobs_equity.csv')); incr+=1
result_df.rename(columns={'geography_group': 'Equity Group', 
                          'jobs_1_mile_walk': 'Jobs within 1-mile Walk',
                        'jobs_3_mile_bike':  'Jobs within 3-mile Bike'}, inplace=True)

result_df['% Total Jobs (1-mile walk)'] = result_df['Jobs within 1-mile Walk']/tot_jobs
result_df['% Total Jobs (3-mile bike)'] = result_df['Jobs within 3-mile Bike']/tot_jobs
result_df['Equity Group'] = ['NOT in '+i for i in result_df['Equity Group']]
output = result_df.to_html(formatters={
    '% Total Jobs (1-mile walk)': '{:0,.1%}'.format,
    '% Total Jobs (3-mile bike)': '{:0,.1%}'.format
}, index=False)
display(HTML(output))